#!/usr/bin/env python

from gi.repository import Cdn
import sys, tempfile, json, os

code = sys.stdin.read()

tmp = tempfile.NamedTemporaryFile()
tmp.write(code)
tmp.flush()

network = Cdn.Network()

try:
    network.load_from_path(tmp.name)
except Exception as e:
    ctx = network.get_parser_context()
    [lstart, lend, cstart, cend, f] = ctx.get_error_location()

    ret = {
        'status': 'error',
        'error': {
            'line': (lstart, lend),
            'column': (cstart, cend),
            'message': str(e).replace(os.path.basename(tmp.name), '<file>'),
        }
    }

    print(json.dumps(ret))
    sys.exit(0)

print(json.dumps({
    'status': 'ok',
}))

# vi:ts=4:et
